import Head from "next/head";
import { Outfit } from "next/font/google";
import SearchCountries from "@/components/SearchCountries";

const outfit = Outfit({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>RestCountries - Frontend Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${outfit.className}`}>
        <SearchCountries></SearchCountries>
      </main>
    </>
  );
}
